### PR TITLE
Lintin' Park: Requesting permission to merge to develop branch

### PR DESCRIPTION
**Pull request by fdezcaminero**
In this project, I cloned many methods related to the Enumerable module:

    each
    each_with_index
    select
    all?
    any?
    none?
    count
    map
    inject

At the very beginning, one of my biggest setbacks was that I wasn't using the methods I was creating for the newer methods. I didn't use each or my_each in the bottom methods. _I did that because I thought it would be recognized as a bigger challenge._ However, all my friends told me that I would get my code sent back if I did it that way. So I used my_each for some of the latter methods.

Second setback: the Ruby docs are very confusing. For instance, the example they use to explain the initial is in a case where the value would be the same with or without the initial. If initial is 1 and symbol is *, that 1 is a neutral element. Not very didactic.

Finally, it took me the longest time to condense the code and write less conditional statements, as required by Rubocop.

### CODE REVIEW

**Review by MauricioRobayo — CHANGES_REQUESTED** [review]
This is looking nice!

The project is working as expected, but you need to make some updates:

* [ ] The project has a descriptive README.md ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)).
* [ ] Pull Request has meaningful title and a short description ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)). Please edit this PR description.

Status: __Request changes__.

**Comment by fdezcaminero** [comment]
The hardest part about this project was having to condense the code a lot. Also, using less conditional statements. Otherwise it would get Rubocop offenses.

Requesting permission to merge to develop branch (as it is done in Git Flow).

**Review by MauricioRobayo — APPROVED** [review]
@fdezcaminero You have done a great job 🚀 I'll approve this but 😣... please edit this PR description to include a short summary of its content as described [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/). You can edit this PR description:

image

And please keep that in mind for the upcoming projects, always include a short description of the PR when you open it.

**Comment by fdezcaminero** [comment]
In this project, I cloned many methods related to the Enumerable module: 

- each
- each_with_index
- select
- all?
- any?
- none?
- count
- map
- inject

At the very beginning, one of my biggest setbacks was that I wasn't using the methods I was creating for the newer methods. I didn't use each or my_each in the bottom methods. _I did that because I thought it would be recognized as a bigger challenge_. However, all my friends told me that  I would get my code sent back if I did it that way. So I used my_each for some of the latter methods.

Second setback: the Ruby docs are very confusing. For instance, the example they use to explain the initial is in a case where the value would be the same with or without the initial. If initial is 1 and symbol is *, that 1 is a neutral element. Not very didactic.

Finally, it took me the longest time to condense the code and write less conditional statements, as required by Rubocop.

**Comment by MauricioRobayo** [comment]
I meant the first message on this PR 🤣, that's where the PR description should go:

image

**Comment by fdezcaminero** [comment]
Hahaha, sorry about that! Didn't see it! I think it's finally fixed! Thank
you so much!

**Pull request merged**
